[tasks.coverage]
description = "Run code coverage (OS-specific)"
script = [
    '''
    if [[ "$CARGO_MAKE_OS" == "linux" ]]; then
        cargo tarpaulin --workspace --all-features --tests --out Html
    elif [[ "$CARGO_MAKE_OS" == "mac" ]]; then
        CARGO_INCREMENTAL=0 RUSTFLAGS="-Cinstrument-coverage" LLVM_PROFILE_FILE="project-%p-%m.profraw" cargo test
        grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o target/coverage/
    elif [[ "$CARGO_MAKE_OS" == "windows" ]]; then
        set CARGO_INCREMENTAL=0
        set RUSTFLAGS=-Cinstrument-coverage
        set LLVM_PROFILE_FILE=project-%p-%m.profraw
        cargo test
        grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o target/coverage/
    fi
    '''
]
